# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ngontjar <ngontjar@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/10/15 15:09:54 by ngontjar          #+#    #+#              #
#    Updated: 2019/10/15 18:29:29 by ngontjar         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = ft_display_file.c

FLAGS = -Wall -Wextra -Werror

NAME = ft_display_file

all: $(NAME)

$(NAME):
	gcc $(FLAGS) $(SRC) -o $(NAME)

clean:


fclean: clean
	rm -f $(NAME)

re: fclean all